### ISSUE TITLE
how to get your dataset?

### ISSUE THREAD

**Issue by wangtao2668129173** [wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection#1]
Thank you for your work. When will the data be open source？

**Comment by wangjk666** [comment]
Yeah. We will make the code and dataset public soon.

**Comment by wangtao2668129173** [comment]
As for the production of deep fake datasets, I can't guarantee the FOMM video effect I made according to the official code. What should I pay attention to in batch production of FOMM dataset.

**Comment by wangtao2668129173** [comment]
王博，能否分享一下你们用的用的驱动视频和图片用的啥，我实在是无法生成合适的视频？

**Comment by wangjk666** [comment]
We use the same driving videos as FF++, and filter out the fake images of low quality (through Retinanet).

**Comment by iRuizeWu** [comment]
emmmm，how to get this dataset?
