### ISSUE TITLE
Fail to run the code

### ISSUE THREAD

**Issue by fortunechen** [wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection#3]
Hi, 

Thx for your open-sourced code. However  I cannot  run the code successfully by

 "python run.py --cfg ./configs/m2tr.yaml "

Could you please provide detailed procedure to run your code? Looking forward for your replying.

**Comment by wangjk666** [comment]
Hi, thanks for reaching out. I have cleaned the code, contact me if you have any other problems.

**Comment by fortunechen** [comment]
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    main()
  File "run.py", line 8, in main
    cfg = load_config(args)
  File "/data10t01/chenzw/forgery_detection/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection-main/tools/utils.py", line 51, in load_config
    with open('./configs/default.yaml', 'r') as file:
FileNotFoundError: [Errno 2] No such file or directory: './configs/default.yaml'

**Comment by fortunechen** [comment]
default.yaml is missing

**Comment by wangjk666** [comment]
fixed

**Comment by fortunechen** [comment]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 59, in _wrap
    fn(i, *args)
  File "/data10t01/chenzw/forgery_detection/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection-main/tools/train.py", line 100, in train
    model = build_model(cfg)
  File "/data10t01/chenzw/forgery_detection/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection-main/M2TR/utils/build_helper.py", line 20, in build_model
    model = MODEL_REGISTRY.get(name)(model_cfg)
  File "/opt/conda/lib/python3.8/site-packages/fvcore/common/registry.py", line 71, in get
    raise KeyError(
KeyError: "No object named 'M2TR' found in 'MODEL' registry!"

**Comment by fortunechen** [comment]
It seems model/dataset/loss haven't been registered

**Comment by fortunechen** [comment]
BTW in line https://github.com/wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection/blob/2cfc2fc06ac1f43801b265207199f37c6190f9a5/tools/utils.py#L54 
`'./configs/' + args.cfg_file` should be `'args.cfg_file`, because the input config path is --cfg ./configs/m2tr.yaml "

**Comment by wangjk666** [comment]
I have registered the models and datasets.

**Comment by fortunechen** [comment]
Thx, I can successfully run your codes now. Maybe there is the bug in validation?

Training contains a resizing operarion:
https://github.com/wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection/blob/a54aefe954440cc5700993deab4d6752e0842126/M2TR/datasets/utils.py#L99
However the operation is missed during valiadation
https://github.com/wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection/blob/a54aefe954440cc5700993deab4d6752e0842126/M2TR/datasets/utils.py#L110

**Comment by wangjk666** [comment]
> Thx, I can successfully run your codes now. Maybe there is the bug in validation?
> 
> Training contains a resizing operarion:
> 
> https://github.com/wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection/blob/a54aefe954440cc5700993deab4d6752e0842126/M2TR/datasets/utils.py#L99
> 
> 
> However the operation is missed during valiadation
> https://github.com/wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection/blob/a54aefe954440cc5700993deab4d6752e0842126/M2TR/datasets/utils.py#L110

The difference is during training, we randomly crop the input image and then resize, but during testing, we only resize the image. That's a common practice in Deepfake detection.

**Comment by fortunechen** [comment]
I agree with you. However in your implmentation,  

there is ONLY resize operation, random crop is missed during traing, because of self.p=-1
there is NO resize operation during testing.

**Comment by wangjk666** [comment]
I have fixed that problem. I set P to the default value 0.5 to achieve the paper results. Thanks for pointing that out.
