### ISSUE TITLE
cfg

### ISSUE THREAD

**Issue by Wrjz** [wangjk666/M2TR-Multi-modal-Multi-scale-Transformers-for-Deepfake-Detection#4]
学长好，运行时的输入“--cfg”是什么意思呢，具体应该怎样输入。
运行会提示错误：run.py: error: the following arguments are required: --cfg
谢谢学长。

**Comment by I-do-not-know-why** [comment]
parser.add_argument(
        "--cfg",
        dest="cfg_file",
        help="Path to the config file",
        default="m2tr.yaml",
        type=str,
    )
